### ISSUE TITLE
ApolloCaffe error

### ISSUE THREAD

**Issue by ShangxuanWu** [jacobandreas/nmn2#19]
Hi,

I am trying to reproduce the results but I got some error like this when running run.sh on VQA dataset:

Traceback (most recent call last):
  File "main.py", line 255, in <module>
    main()
  File "main.py", line 31, in main
    do_iter(task.train, model, config, train=True)
  File "main.py", line 97, in do_iter
    batch_data, model, config, train, vis)
  File "main.py", line 118, in do_batch
    predictions = forward(data, model, config, train, vis)
  File "main.py", line 170, in forward
    dropout=(train and config.opt.dropout), deterministic=not train)
  File "/mnt/sdc1/shangxuan/775/nmn2/models/nmn.py", line 440, in forward
    question_hidden = self.forward_question(question_data, dropout)
  File "/mnt/sdc1/shangxuan/775/nmn2/models/nmn.py", line 648, in forward_question
    bottoms=[word], param_names=[wordvec_param]))
  File "/mnt/sdc1/shangxuan/775/apollocaffe/python/apollocaffe/layers/caffe_layers.py", line 203, in __init__
    super(Wordvec, self).__init__(self, name, kwargs)
  File "/mnt/sdc1/shangxuan/775/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 6, in __init__
    self.parse(sublayer, name, kwargs)
  File "/mnt/sdc1/shangxuan/775/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 57, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
AttributeError: Layer Wordvec has no keyword argument vocab_size=3591

I am using your fork of Apollo Caffe, so I am not sure where the problem goes.

**Comment by ShangxuanWu** [comment]
[https://github.com/Russell91/apollocaffe/issues/65](url) This seems a workaround.
