### ISSUE TITLE
 raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))

### ISSUE THREAD

**Issue by haibin894609937** [jacobandreas/nmn2#23]
Hi,I meet an error,,,,
2017-07-21 12:17:32,576 DEBUG    [root] prepared indices
2017-07-21 12:55:22,728 DEBUG    [root] computed image feature normalizers
2017-07-21 12:55:22,789 DEBUG    [root] using cvpr chooser
2017-07-21 12:57:36,539 INFO     [root] TRAIN2014, VAL2014:
2017-07-21 12:57:36,540 INFO     [root] 369861 items
2017-07-21 12:57:36,540 INFO     [root] 2002 answers
2017-07-21 12:57:36,541 INFO     [root] 877 predicates
2017-07-21 12:57:36,541 INFO     [root] 3591 words
2017-07-21 12:57:36,541 INFO     [root] 
2017-07-21 12:57:56,250 INFO     [root] TEST-DEV2015:
2017-07-21 12:57:56,250 INFO     [root] 60864 items
2017-07-21 12:57:56,250 INFO     [root] 2002 answers
2017-07-21 12:57:56,251 INFO     [root] 877 predicates
2017-07-21 12:57:56,251 INFO     [root] 3591 words
2017-07-21 12:57:56,251 INFO     [root] 
2017-07-21 12:59:02,813 INFO     [root] TEST2015:
2017-07-21 12:59:02,813 INFO     [root] 244302 items
2017-07-21 12:59:02,814 INFO     [root] 2002 answers
2017-07-21 12:59:02,814 INFO     [root] 877 predicates
2017-07-21 12:59:02,814 INFO     [root] 3591 words
2017-07-21 12:59:02,814 INFO     [root] 
Traceback (most recent call last):
  File "main.py", line 255, in <module>
    main()
  File "main.py", line 31, in main
    do_iter(task.train, model, config, train=True)
  File "main.py", line 97, in do_iter
    batch_data, model, config, train, vis)
  File "main.py", line 118, in do_batch
    predictions = forward(data, model, config, train, vis)
  File "main.py", line 170, in forward
    dropout=(train and config.opt.dropout), deterministic=not train)
  File "/disk3/hbliu/vqa/nmn2/models/nmn.py", line 440, in forward
    question_hidden = self.forward_question(question_data, dropout)
  File "/disk3/hbliu/vqa/nmn2/models/nmn.py", line 648, in forward_question
    bottoms=[word], param_names=[wordvec_param]))
  File "/home/hbliu/disk3/vqa/nmn2/apollocaffe/python/apollocaffe/layers/caffe_layers.py", line 203, in __init__
    super(Wordvec, self).__init__(self, name, kwargs)
  File "/home/hbliu/disk3/vqa/nmn2/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 6, in __init__
    self.parse(sublayer, name, kwargs)
  File "/home/hbliu/disk3/vqa/nmn2/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 57, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
AttributeError: Layer Wordvec has no keyword argument vocab_size=3591

**Comment by haibin894609937** [comment]
@jacobandreas

**Comment by jacobandreas** [comment]
Are you using my ApolloCaffe fork? Haven't seen this error before. In any case this codebase is kind of out-of-date---you're better off using https://github.com/ronghanghu/n2nmn.

**Comment by haibin894609937** [comment]
I use your apollocaffe fork , thanks for your advice
