### ISSUE TITLE
'Tile' is not defined

### ISSUE THREAD

**Issue by suraj-vantigodi** [jacobandreas/nmn2#7]
I do not understand this error. Kindly help me out. And is net.f(Tile[]) even required? what is it needed for?

```
`Traceback (most recent call last):
File "main.py", line 257, in <module>
main()
File "main.py", line 31, in main
  do_iter(task.train, model, config, train=True)
File "main.py", line 99, in do_iter
batch_data, model, config, train, vis)
File "main.py", line 120, in do_batch
predictions = forward(data, model, config, train, vis)
File "main.py", line 172, in forward
dropout=(train and config.opt.dropout), deterministic=not train)
File "/home/ubuntu/Caffe/nmn2/models/nmn.py", line 443, in forward
  deterministic)
File "/home/ubuntu/Caffe/nmn2/models/nmn.py", line 557, in forward_layout
net.f(Tile(tile_question, axis=1, tiles=n_layouts,bottoms=[proj_question])) 
NameError: global name 'Tile' is not defined
`
```

If I comment the lines in nmn.py , which have Tile, I get error below,

```
`Traceback (most recent call last):
 File "main.py", line 257, in <module>
  main()
 File "main.py", line 31, in main
 do_iter(task.train, model, config, train=True)
 File "main.py", line 99, in do_iter
  batch_data, model, config, train, vis)
 File "main.py", line 120, in do_batch
   predictions = forward(data, model, config, train, vis)
 File "main.py", line 172, in forward
 dropout=(train and config.opt.dropout), deterministic=not train)
 File "/home/ubuntu/Caffe/nmn2/models/nmn.py", line 443, in forward
   deterministic)
 File "/home/ubuntu/Caffe/nmn2/models/nmn.py", line 575, in forward_layout
  net.f(Eltwise(sum, "SUM", bottoms=[tile_question, concat_layer]))
  File "python/apollocaffe/cpp/_apollocaffe.pyx", line 287, in apollocaffe.cpp._apollocaffe.ApolloNet.f              (python/apollocaffe/cpp/_apollocaffe.cpp:7848)
  RuntimeError: src/caffe/apollonet.cpp(@209): Could not find bottom: 'LAYOUT_tile2_question' for   layer: LAYOUT_sum
 `
```

**Comment by jacobandreas** [comment]
Please read the README. You are using the wrong version of ApolloCaffe.

**Comment by suraj-vantigodi** [comment]
Yes, sorry for my negligence. Its running now.
